"""Leave-one-pillar-out signal test for the E_macro feature matrix.

The question this answers: **do the six pillars carry shared county-level
structure that county size and state geography do not already explain?**

Every crossvalidation in this repo so far has been bivariate -- one scalar
against another, permutation-tested. That design can only see pairwise linear
association, and the pillar-pair sweep showed most of what it found was county
size. This test is the multivariate version, and it needs no external label:

    for each target column t belonging to pillar P
        baseline  = size measures + state fixed effects
        full      = baseline + every feature from the five pillars != P
        lift      = R2_out-of-fold(full) - R2_out-of-fold(baseline)

A positive lift means the other five pillars know something about t beyond how
big and where the county is. That is the minimum bar for the matrix to be worth
embedding at all: if the pillars cannot predict each other past size, they are
six independent noise sources plus a population variable, and no fusion of them
will produce signal that was not there.

The null is generated by row-shuffling the other-pillar block, which breaks the
county alignment while preserving each feature's marginal distribution and the
baseline's fit. Reported p-values are empirical over `N_NULL_REPS` shuffles.
Note what that null is and is not: it asks whether the real features beat
*random features of the same shape*, and shuffled predictors actively hurt an
out-of-fold fit, so the null lift sits below zero. A target can therefore clear
the null with a lift that is itself negative. `lift` is the practical measure;
`p` only certifies that a positive lift is not noise.

Every lift is reported twice, raw and with the restating columns removed from the
predictors (`lift_ablated`). USDA builds its industry-dependence flags from
industry employment and earnings shares -- the same underlying quantity QCEW's
location quotients measure -- so `high_manufacturing` predicting the
manufacturing LQ is two federal products restating one fact, not two agencies
corroborating each other. Source A's `has_metro_attachment` is the same
phenomenon across a different pair: it fires when a Wikipedia intro states the
county belongs to a metropolitan statistical area, which is the OMB delineation
Source F's `metro_2023` reports directly. The gap between the two columns is how
much of a result is that overlap.

Two things this test deliberately does **not** claim:

- It is not evidence that the matrix predicts any downstream outcome. There is
  no such label in this repo. Cross-pillar predictability is necessary for that,
  not sufficient.
- A pillar with low lift is not thereby useless. Being unpredictable from the
  other five is also what an independent information source looks like. Read
  lift as "corroborated by the rest of the matrix", not as "good".
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.impute import SimpleImputer
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from pillar_matrix import SIZE_FEATURES, build_matrix, other_pillar_columns
from stats_utils import benjamini_hochberg

# Matches every other crossvalidation script in this project.
RANDOM_SEED: int = 42
N_FOLDS: int = 5
N_NULL_REPS: int = 99
FDR_ALPHA: float = 0.05
MIN_TARGET_OBSERVATIONS: int = 500

# Source F columns that restate industry composition. USDA derives its typology
# from industry employment and earnings shares, so these overlap QCEW's location
# quotients by construction rather than by evidence. Held out to produce
# `lift_ablated`; the distress flags, `metro_2023` and `distress_count` are not
# industry measures and stay in.
F_INDUSTRY_COLUMNS: tuple[str, ...] = (
    "high_farming",
    "high_mining",
    "high_manufacturing",
    "high_government",
    "high_recreation",
    "nonspecialized",
    "industry_dependence_none",
    "industry_dependence_farming",
    "industry_dependence_mining",
    "industry_dependence_manufacturing",
    "industry_dependence_government",
    "industry_dependence_recreation",
)

# Source A columns that restate a fact another pillar also reports, for the same
# reason F_INDUSTRY_COLUMNS does: `has_metro_attachment` fires when a county's
# Wikipedia intro says it belongs to a metropolitan or micropolitan statistical
# area, and Source F's `metro_2023` is that same OMB delineation read from USDA.
# One is an encyclopedia repeating a federal definition, the other is the federal
# definition -- agreement between them is bookkeeping, not corroboration.
#
# Source A's outright diagnostics (`has_usda_echo`, `n_body_sections`) need no
# entry here: `pillar_matrix` keeps them out of the matrix entirely.
A_RESTATEMENT_COLUMNS: tuple[str, ...] = ("has_metro_attachment",)

# Everything held out of the ablated design. Both entries above are the same
# phenomenon -- two products restating one underlying fact -- so they share one
# ablation rather than getting a column each, which keeps `lift_ablated`
# interpretable as "lift with definitional overlap removed".
RESTATEMENT_COLUMNS: tuple[str, ...] = F_INDUSTRY_COLUMNS + A_RESTATEMENT_COLUMNS

# RidgeCV search grid. The matrix is wide relative to its 3,143 rows once state
# dummies and missingness indicators are added, so the penalty matters.
RIDGE_ALPHAS: tuple[float, ...] = (0.1, 1.0, 10.0, 100.0, 1000.0)

REPO_ROOT: Path = Path(__file__).resolve().parent.parent
OUTPUTS_DIR: Path = REPO_ROOT / "outputs"
ANALYSIS_DIR: Path = REPO_ROOT / "analysis-output" / "cross-source"

OUTPUT_CSV_PATH: Path = OUTPUTS_DIR / "pillar_matrix_signal.csv"
OUTPUT_STATS_PATH: Path = ANALYSIS_DIR / "pillar_matrix_signal_stats.json"

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class Target:
    """One continuous column to be predicted from the other five pillars.

    Attributes:
        pillar: Owning pillar letter, "A" through "F".
        column: Column name in the assembled matrix.
        label: Human-readable description used in reports.
    """

    pillar: str
    column: str
    label: str


# Continuous targets only. Binary columns (metro status, the typology and
# distress flags, `low_return_flag`) stay in the predictor blocks but are not
# scored here -- R2 on a Bernoulli outcome is not comparable to R2 on a
# continuous one, and mixing them would make the per-pillar means meaningless.
# Source B contributes all 20 sector LQs because "which sector" was the finding
# that rescued that pillar; Source D's commodity-group tonnages are predictors
# only, since they sum to the totals already targeted.
STATIC_TARGETS: tuple[Target, ...] = (
    Target("A", "content_length", "intro-text length"),
    Target("C", "unemployment_velocity", "unemployment velocity"),
    Target("C", "unemployment_rate_latest", "unemployment rate (level)"),
    Target("C", "gdp_velocity_pct", "GDP velocity (normalized)"),
    Target("D", "log_total_tons", "freight tonnage (log10)"),
    Target("D", "out_partner_hhi", "outbound partner concentration"),
    Target("D", "in_partner_hhi", "inbound partner concentration"),
    Target("E", "capital_to_wage_ratio", "capital-to-wage ratio"),
    Target("F", "distress_count", "demographic distress count"),
)


def configure_logging() -> None:
    """Configure root logging format/level for script execution."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    )


def build_targets(blocks: dict[str, list[str]], naics_labels: dict[str, str]) -> list[Target]:
    """Expand the static target list with Source B's 20 sector LQ columns.

    Args:
        blocks: Pillar-to-columns mapping from `build_matrix`.
        naics_labels: NAICS 2-digit code to sector name.

    Returns:
        Every target to be scored, in pillar order.
    """
    lq_targets = [
        Target("B", col, f"{naics_labels.get(col.replace('lq_emp_', ''), col)} LQ")
        for col in blocks["B"]
        if col.startswith("lq_emp_")
    ]
    targets = [t for t in STATIC_TARGETS if t.pillar == "A"]
    targets += lq_targets
    targets += [t for t in STATIC_TARGETS if t.pillar != "A"]
    return targets


def build_baseline_design(matrix: pd.DataFrame) -> pd.DataFrame:
    """Assemble the size-plus-geography control matrix.

    State fixed effects enter as dummy columns. The encoding is fitted on the
    full matrix rather than per fold, which is safe here because it depends only
    on `state_fips` and never on the target.

    Args:
        matrix: Feature matrix from `build_matrix`.

    Returns:
        DataFrame of size features plus one dummy column per state, aligned to
        `matrix`'s index.
    """
    state_dummies = pd.get_dummies(matrix["state_fips"], prefix="state", dtype="float")
    return pd.concat([matrix[list(SIZE_FEATURES)], state_dummies], axis=1)


def _ridge_pipeline(alpha: float | None = None) -> Pipeline:
    """Build the impute-scale-ridge pipeline used for every ridge fit.

    Median imputation with an added missingness indicator is the right default
    for this matrix: BLS suppresses ~35% of the LQ cells, and "suppressed" is
    itself informative about county size and sector structure, so the indicator
    has to survive into the model rather than being imputed away.

    Args:
        alpha: Fixed ridge penalty. When None, RidgeCV selects one from
            RIDGE_ALPHAS by internal generalized crossvalidation.

    Returns:
        Unfitted sklearn Pipeline.
    """
    estimator = RidgeCV(alphas=RIDGE_ALPHAS) if alpha is None else Ridge(alpha=alpha)
    return Pipeline(
        [
            ("impute", SimpleImputer(strategy="median", add_indicator=True)),
            ("scale", StandardScaler()),
            ("model", estimator),
        ]
    )


def _oof_r2(design: np.ndarray, y: np.ndarray, pipeline: Pipeline, folds: KFold) -> float:
    """Out-of-fold R2 for one design matrix.

    Args:
        design: Predictor array.
        y: Target vector.
        pipeline: Unfitted estimator pipeline.
        folds: Crossvalidation splitter.

    Returns:
        R2 computed once over the concatenated out-of-fold predictions, which
        is the pooled estimate rather than a mean of per-fold R2 values.
    """
    predictions = cross_val_predict(pipeline, design, y, cv=folds)
    return float(r2_score(y, predictions))


def _selected_alpha(design: np.ndarray, y: np.ndarray) -> float:
    """Fit RidgeCV once to pick the penalty reused across the null reps.

    Refitting RidgeCV inside every one of the N_NULL_REPS shuffles would triple
    the runtime for no benefit -- the penalty is a property of the design's
    shape and conditioning, not of the county alignment being shuffled.

    Args:
        design: Predictor array.
        y: Target vector.

    Returns:
        Selected ridge penalty.
    """
    pipeline = _ridge_pipeline()
    pipeline.fit(design, y)
    return float(pipeline.named_steps["model"].alpha_)


def score_target(
    matrix: pd.DataFrame,
    blocks: dict[str, list[str]],
    baseline: pd.DataFrame,
    target: Target,
) -> dict[str, float | str | int] | None:
    """Run the leave-one-pillar-out test for a single target column.

    Args:
        matrix: Feature matrix from `build_matrix`.
        blocks: Pillar-to-columns mapping.
        baseline: Size-plus-state design from `build_baseline_design`.
        target: The column to predict.

    Returns:
        Result record, or None if the target has too few observations.
    """
    rows = matrix[target.column].notna()
    n = int(rows.sum())
    if n < MIN_TARGET_OBSERVATIONS:
        logger.warning("skipping %s: only %d non-null rows", target.column, n)
        return None

    y = matrix.loc[rows, target.column].to_numpy(dtype="float64")
    predictors = other_pillar_columns(blocks, target.pillar)

    base_design = baseline.loc[rows].to_numpy(dtype="float64")
    other_design = matrix.loc[rows, predictors].to_numpy(dtype="float64")
    full_design = np.hstack([base_design, other_design])

    folds = KFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_SEED)
    r2_baseline = _oof_r2(base_design, y, _ridge_pipeline(), folds)
    r2_full = _oof_r2(full_design, y, _ridge_pipeline(), folds)
    lift = r2_full - r2_baseline

    # Same test with the restating columns held out, isolating the share of the
    # lift that is definitional overlap rather than independent corroboration.
    ablated_predictors = [col for col in predictors if col not in RESTATEMENT_COLUMNS]
    ablated_design = np.hstack(
        [base_design, matrix.loc[rows, ablated_predictors].to_numpy(dtype="float64")]
    )
    lift_ablated = _oof_r2(ablated_design, y, _ridge_pipeline(), folds) - r2_baseline

    # Nonlinear cross-check. Gradient boosting handles the NaNs natively, so it
    # sees the suppressed LQ cells as missing rather than median-filled.
    gbm = HistGradientBoostingRegressor(random_state=RANDOM_SEED)
    gbm_lift = _oof_r2(full_design, y, gbm, folds) - _oof_r2(base_design, y, gbm, folds)

    alpha = _selected_alpha(full_design, y)
    rng = np.random.default_rng(RANDOM_SEED)
    null_lifts = np.empty(N_NULL_REPS)
    for rep in range(N_NULL_REPS):
        shuffled = np.hstack([base_design, other_design[rng.permutation(n)]])
        null_lifts[rep] = _oof_r2(shuffled, y, _ridge_pipeline(alpha), folds) - r2_baseline

    p_value = (np.sum(null_lifts >= lift) + 1) / (N_NULL_REPS + 1)

    return {
        "pillar": target.pillar,
        "column": target.column,
        "label": target.label,
        "n": n,
        "r2_baseline": r2_baseline,
        "r2_full": r2_full,
        "lift": lift,
        "lift_ablated": lift_ablated,
        "lift_gbm": gbm_lift,
        "null_lift_mean": float(null_lifts.mean()),
        "null_lift_p95": float(np.percentile(null_lifts, 95)),
        "p": float(p_value),
    }


def run_sweep(matrix: pd.DataFrame, blocks: dict[str, list[str]], targets: list[Target]) -> pd.DataFrame:
    """Score every target and apply one FDR correction across the whole sweep.

    Args:
        matrix: Feature matrix from `build_matrix`.
        blocks: Pillar-to-columns mapping.
        targets: Targets to score.

    Returns:
        One row per scored target, sorted by lift descending.
    """
    baseline = build_baseline_design(matrix)
    records = []
    for target in targets:
        record = score_target(matrix, blocks, baseline, target)
        if record is None:
            continue
        records.append(record)
        logger.info(
            "%s %-28s n=%4d  base R2=%+.3f  lift=%+.3f  ablated=%+.3f  p=%.3f",
            record["pillar"],
            record["column"],
            record["n"],
            record["r2_baseline"],
            record["lift"],
            record["lift_ablated"],
            record["p"],
        )

    results = pd.DataFrame(records)
    results["q"] = benjamini_hochberg(results["p"].tolist())
    results["significant"] = results["q"] < FDR_ALPHA
    # The headline judgement: beat the size-plus-state baseline, beat the
    # shuffled-feature null, and still beat the baseline once USDA's industry
    # flags are held out.
    results["carries_signal"] = (
        results["significant"] & (results["lift"] > 0) & (results["lift_ablated"] > 0)
    )
    return results.sort_values("lift_ablated", ascending=False).reset_index(drop=True)


def summarize(results: pd.DataFrame) -> dict[str, object]:
    """Collapse per-target results to the numbers the findings report quotes.

    Args:
        results: Output of `run_sweep`.

    Returns:
        JSON-serializable summary.
    """
    by_pillar = results.groupby("pillar").agg(
        n_targets=("column", "size"),
        n_carrying_signal=("carries_signal", "sum"),
        mean_lift=("lift", "mean"),
        mean_lift_ablated=("lift_ablated", "mean"),
        max_lift_ablated=("lift_ablated", "max"),
        mean_r2_baseline=("r2_baseline", "mean"),
    )
    return {
        "n_targets": int(len(results)),
        "n_significant": int(results["significant"].sum()),
        "n_carrying_signal": int(results["carries_signal"].sum()),
        "n_folds": N_FOLDS,
        "n_null_reps": N_NULL_REPS,
        "random_seed": RANDOM_SEED,
        "mean_lift": float(results["lift"].mean()),
        "mean_lift_ablated": float(results["lift_ablated"].mean()),
        "median_lift_ablated": float(results["lift_ablated"].median()),
        "mean_lift_gbm": float(results["lift_gbm"].mean()),
        "mean_r2_baseline": float(results["r2_baseline"].mean()),
        "definitional_share_of_mean_lift": float(
            1 - results["lift_ablated"].mean() / results["lift"].mean()
        ),
        "best_target": results.iloc[0]["column"],
        "best_lift_ablated": float(results.iloc[0]["lift_ablated"]),
        "by_pillar": json.loads(by_pillar.to_json(orient="index")),
    }


def main() -> None:
    """Build the matrix, run the sweep, and write CSV plus stats JSON."""
    configure_logging()

    import sys

    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    from analyze_source_b_industry_mix import NAICS2_LABELS

    matrix, blocks = build_matrix()
    targets = build_targets(blocks, NAICS2_LABELS)
    logger.info("scoring %d targets across %d pillars", len(targets), len(blocks))

    results = run_sweep(matrix, blocks, targets)
    stats = summarize(results)

    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)
    results.to_csv(OUTPUT_CSV_PATH, index=False)
    OUTPUT_STATS_PATH.write_text(json.dumps(stats, indent=2))

    logger.info("wrote %s", OUTPUT_CSV_PATH)
    logger.info("wrote %s", OUTPUT_STATS_PATH)
    logger.info(
        "%d of %d targets carry signal (FDR q < %.2f, positive lift after ablation) | "
        "mean lift %+.3f raw, %+.3f ablated",
        stats["n_carrying_signal"],
        stats["n_targets"],
        FDR_ALPHA,
        stats["mean_lift"],
        stats["mean_lift_ablated"],
    )


if __name__ == "__main__":
    main()
